module.exports = [
    {
        name: "Classic Spaghetti Bolognese",
        summary: "A delicious and hearty Italian pasta dish.",
        cooktime: 30,
        ingredients: "Spaghetti, ground beef, onions, garlic, tomatoes, tomato paste, olive oil, basil, oregano, salt, pepper, Parmesan cheese",
        directions: "1. Cook spaghetti according to package instructions. 2. In a large skillet, heat olive oil over medium heat and sauté onions and garlic. 3. Add ground beef and cook until browned. 4. Stir in tomatoes, tomato paste, basil, oregano, salt, and pepper. 5. Simmer sauce for 15 minutes. 6. Serve sauce over cooked spaghetti and sprinkle with Parmesan cheese.",
    },
    {
        name: "Chicken Alfredo",
        summary: "Creamy and flavorful pasta with tender chicken.",
        cooktime: 25,
        ingredients: "Fettuccine pasta, chicken breast, heavy cream, butter, garlic, Parmesan cheese, salt, pepper, parsley",
        directions: "1. Cook fettuccine according to package instructions. 2. In a separate pan, cook chicken until done. 3. In a saucepan, melt butter and sauté garlic. 4. Pour in heavy cream and bring to a simmer. 5. Stir in grated Parmesan cheese until sauce thickens. 6. Add cooked chicken to the sauce and simmer for a few minutes. 7. Serve Alfredo sauce over fettuccine and garnish with parsley.",
    },
    {
        name: "Vegetable Stir-Fry",
        summary: "A healthy and colorful mix of fresh vegetables.",
        cooktime: 20,
        ingredients: "Broccoli, carrots, bell peppers, snap peas, mushrooms, tofu, soy sauce, sesame oil, ginger, garlic, red pepper flakes",
        directions: "1. Cut vegetables into bite-sized pieces. 2. In a wok or large skillet, heat sesame oil and sauté ginger and garlic. 3. Add vegetables and stir-fry until tender-crisp. 4. Add tofu and soy sauce, and continue to stir-fry for a few more minutes. 5. Sprinkle with red pepper flakes for some heat. 6. Serve the vegetable stir-fry over steamed rice.",
    },
    {
        name: "Cheesy Baked Ziti",
        summary: "A comforting baked pasta dish with melted cheese.",
        cooktime: 40,
        ingredients: "Ziti pasta, ricotta cheese, mozzarella cheese, marinara sauce, Parmesan cheese, eggs, basil, salt, pepper",
        directions: "1. Cook ziti according to package instructions. 2. In a bowl, mix ricotta cheese, eggs, basil, salt, and pepper. 3. In a baking dish, layer cooked ziti, ricotta mixture, marinara sauce, and mozzarella cheese. 4. Repeat the layers and top with Parmesan cheese. 5. Bake in the oven at 350°F (175°C) until cheese is bubbly and golden. 6. Let it cool slightly before serving.",
    },
    {
        name: "Creamy Tomato Basil Soup",
        summary: "A rich and velvety soup with the flavors of fresh basil and tomatoes.",
        cooktime: 35,
        ingredients: "Tomatoes, onions, garlic, vegetable broth, heavy cream, basil leaves, butter, salt, pepper",
        directions: "1. In a pot, melt butter and sauté onions and garlic. 2. Add chopped tomatoes and cook until soft. 3. Pour in vegetable broth and simmer for 20 minutes. 4. Use an immersion blender to puree the soup until smooth. 5. Stir in heavy cream and fresh basil leaves. 6. Season with salt and pepper to taste. 7. Serve the creamy tomato basil soup with crusty bread.",
    },
    {
        name: "Beef Tacos",
        summary: "Flavorful and satisfying beef tacos with all the toppings.",
        cooktime: 30,
        ingredients: "Ground beef, taco seasoning, tortillas, lettuce, tomatoes, cheddar cheese, salsa, sour cream",
        directions: "1. In a skillet, cook ground beef until browned. 2. Stir in taco seasoning and cook according to the package instructions. 3. Warm tortillas in a separate pan. 4. Assemble the tacos by filling tortillas with seasoned beef, shredded lettuce, diced tomatoes, cheddar cheese, salsa, and a dollop of sour cream. 5. Serve the beef tacos with your favorite side dishes.",
    },
    {
        name: "Homemade Margherita Pizza",
        summary: "Classic pizza with tomato, mozzarella, and fresh basil.",
        cooktime: 25,
        ingredients: "Pizza dough, tomato sauce, mozzarella cheese, fresh basil leaves, olive oil, salt, pepper",
        directions: "1. Preheat the oven to 475°F (245°C). 2. Roll out the pizza dough on a floured surface. 3. Spread tomato sauce over the dough. 4. Sprinkle shredded mozzarella cheese on top. 5. Tear fresh basil leaves and scatter them over the pizza. 6. Drizzle olive oil and season with salt and pepper. 7. Bake the Margherita pizza in the oven until the crust is golden and the cheese is bubbly. 8. Slice and enjoy!",
    },
    {
        name: "Chicken and Broccoli Stir-Fry",
        summary: "Quick and healthy stir-fry with tender chicken and crisp broccoli.",
        cooktime: 20,
        ingredients: "Chicken breast, broccoli, soy sauce, oyster sauce, garlic, ginger, sesame oil, red pepper flakes",
        directions: "1. Cut chicken breast into bite-sized pieces. 2. In a wok or large skillet, stir-fry chicken until cooked. 3. Add broccoli and cook until tender-crisp. 4. In a small bowl, mix soy sauce, oyster sauce, minced garlic, grated ginger, and red pepper flakes. 5. Pour the sauce over the chicken and broccoli. 6. Drizzle with sesame oil for added flavor. 7. Serve the chicken and broccoli stir-fry over steamed rice.",
    },
    {
        name: "Chocolate Chip Cookies",
        summary: "Classic homemade cookies with gooey chocolate chips.",
        cooktime: 15,
        ingredients: "All-purpose flour, butter, brown sugar, granulated sugar, eggs, vanilla extract, baking soda, salt, chocolate chips",
        directions: "1. Preheat the oven to 350°F (175°C). 2. In a bowl, cream butter and sugars until light and fluffy. 3. Beat in eggs one at a time and add vanilla extract. 4. In a separate bowl, whisk together flour, baking soda, and salt. 5. Gradually add the dry ingredients to the wet ingredients. 6. Stir in chocolate chips. 7. Drop spoonfuls of dough onto a baking sheet. 8. Bake the cookies in the oven for about 10-12 minutes until golden. 9. Allow the cookies to cool on a wire rack before serving.",
    },
    {
        name: "Creamy Garlic Mashed Potatoes",
        summary: "Smooth and creamy mashed potatoes with a hint of garlic.",
        cooktime: 30,
        ingredients: "Potatoes, butter, milk, garlic, salt, pepper, chives",
        directions: "1. Peel and chop potatoes into small chunks. 2. Boil the potatoes in salted water until tender. 3. Drain the potatoes and return them to the pot. 4. In a saucepan, melt butter and sauté minced garlic until fragrant. 5. Mash the potatoes and gradually add melted butter, garlic, and milk. 6. Continue mashing until smooth and creamy. 7. Season with salt and pepper. 8. Garnish with chopped chives before serving.",
    },
]